# Generated by Django 5.1 on 2024-09-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('id_admin', models.BooleanField(default=False)),
                ('id_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
